# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2.1

jobs:
  test:
    parameters:
      php-version:
        type: string
    docker:
      - image: circleci/php:<< parameters.php-version >>-node-browsers
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.17
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "composer.json" }}
            - v1-dependencies-
      - run: composer install -n --prefer-dist
      - save_cache:
          key: v1-dependencies-{{ checksum "composer.json" }}
          paths:
            - ./vendor
      - run: ./vendor/bin/phpunit
workflows:
  all-phps:
    jobs:
      - test:
          matrix:
            parameters:
              php-version: ["7.3", "7.4", "8.0"]
